apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sentry-db-init
  name: sentry-db-init
#  namespace: local
spec:
  template:
    metadata:
      labels:
        app: sentry-db-init
    spec:
      restartPolicy: Never
      containers:
      - name: sentry-db-init
        image: "sentry:8.20"
        command: ["sentry","upgrade","--noinput"]
        env:
          - name: SENTRY_SECRET_KEY
            value: "92jksjhd78238jsd78r732h7290"
          - name: SENTRY_DB_USER
            value: "sentry"
          - name: SENTRY_DB_NAME
            value: "sentry"
          - name: SENTRY_DB_PASSWORD
            value: "ymzndl33SNwdm"
          - name: SENTRY_POSTGRES_HOST
            value: sentry-postgresql
          - name: SENTRY_POSTGRES_PORT
            value: "5432"
          - name: SENTRY_REDIS_HOST
            value: sentry-redis
          - name: SENTRY_REDIS_PASSWORD
            value: "L9Ut7625E0dDdgf"
          - name: SENTRY_REDIS_PORT
            value: "6379"

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sentry-user-init
  name: sentry-user-init
#  namespace: local
spec:
  template:
    metadata:
      labels:
        app: sentry-user-init
    spec:
      restartPolicy: Never
      containers:
      - name: sentry-user-init
        image: "sentry:8.20"
        command: ["sentry","createuser","--no-input","--email", "admin@sentry.local", "--superuser","--password","$(SENTRY_USER_PASSWORD)"]
        env:
          - name: SENTRY_SECRET_KEY
            value: "92jksjhd78238jsd78r732h7290"
          - name: SENTRY_DB_USER
            value: "sentry"
          - name: SENTRY_DB_NAME
            value: "sentry"
          - name: SENTRY_DB_PASSWORD
            value: "ymzndl33SNwdm"
          - name: SENTRY_POSTGRES_HOST
            value: sentry-postgresql
          - name: SENTRY_POSTGRES_PORT
            value: "5432"
          - name: SENTRY_REDIS_HOST
            value: sentry-redis
          - name: SENTRY_REDIS_PASSWORD
            value: "L9Ut7625E0dDdgf"
          - name: SENTRY_REDIS_PORT
            value: "6379"
          - name: SENTRY_USER_PASSWORD
            value: "sentryMt2018"
