apiVersion: v1
kind: Service
metadata:
  name: sentry-redis
#  namespace: local
spec:
  type: ClusterIP
  ports:
  - name: redis-port
    port: 6379
    targetPort: redis-port
  selector:
    app: sentry-redis

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sentry-redis
  name: sentry-redis
#  namespace: local
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry-redis
    spec:
      containers:
      - name: sentry-redis
        image: "bitnami/redis:3.2.9-r2"
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASSWORD
          value: "L9Ut7625E0dDdgf"
        ports:
        - name: redis-port
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi

        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis
      volumes:
      - name: redis-data
        emptyDir: {}